// Club and stadium catalogue for the competitions Robbedoes covers.
// Coordinates are approximate (usually within a few hundred metres, at worst a few kilometres)
// and are only used for straight-line distances. Aliases must contain every spelling a data
// provider uses; tests/clubs.test.ts checks that the current season's names all resolve.
export type Club = {
  id: string;
  name: string;
  aliases: string[];
  country: string;
  stadium: string;
  city: string;
  lat: number;
  lon: number;
  timezone: string;
  website: string | null;
  color: string;
};

type Row = [
  id: string,
  name: string,
  aliases: string[],
  stadium: string,
  city: string,
  lat: number,
  lon: number,
  website: string | null,
  color?: string,
  timezone?: string,
];

const group = (country: string, timezone: string, rows: Row[]): Club[] =>
  rows.map(
    ([id, name, aliases, stadium, city, lat, lon, website, color, tz]) => ({
      id,
      name,
      aliases: [name, ...aliases],
      country,
      stadium,
      city,
      lat,
      lon,
      timezone: tz ?? timezone,
      website: website ? `https://${website}` : null,
      color: color ?? "#d7d7d7",
    }),
  );

export const COUNTRY_NAMES: Record<string, string> = {
  NL: "Nederland",
  DE: "Duitsland",
  EN: "Engeland",
  WA: "Wales",
  ES: "Spanje",
  IT: "Italië",
  FR: "Frankrijk",
  MC: "Monaco",
  PT: "Portugal",
  SC: "Schotland",
  BE: "België",
  AT: "Oostenrijk",
  DK: "Denemarken",
  SE: "Zweden",
  NO: "Noorwegen",
  GR: "Griekenland",
  TR: "Turkije",
};

// prettier-ignore
export const CLUBS: Club[] = [
  ...group("NL", "Europe/Amsterdam", [
    ["ado-den-haag", "ADO Den Haag", ["ADO"], "Bingoal Stadion", "Den Haag", 52.0627, 4.3831, "adodenhaag.nl", "#e5c831"],
    ["ajax", "Ajax", ["AFC Ajax", "Ajax Amsterdam"], "Johan Cruijff ArenA", "Amsterdam", 52.3144, 4.9419, "ajax.nl", "#e03a4a"],
    ["az", "AZ", ["AZ Alkmaar"], "AFAS Stadion", "Alkmaar", 52.6128, 4.7424, "az.nl", "#e0303a"],
    ["groningen", "FC Groningen", ["Groningen"], "Euroborg", "Groningen", 53.2067, 6.5919, "fcgroningen.nl", "#39a45b"],
    ["twente", "FC Twente", ["FC Twente '65", "Twente", "Twente Enschede"], "De Grolsch Veste", "Enschede", 52.2366, 6.8376, "fctwente.nl", "#e0303a"],
    ["utrecht", "FC Utrecht", ["Utrecht"], "Stadion Galgenwaard", "Utrecht", 52.0783, 5.1458, "fcutrecht.nl", "#d53741"],
    ["feyenoord", "Feyenoord", ["Feyenoord Rotterdam"], "De Kuip", "Rotterdam", 51.8939, 4.5231, "feyenoord.com", "#e8323b"],
    ["fortuna-sittard", "Fortuna Sittard", ["Fortuna"], "Fortuna Sittard Stadion", "Sittard", 51.0001, 5.8458, "fortunasittard.nl", "#f2d21b"],
    ["go-ahead-eagles", "Go Ahead Eagles", ["GA Eagles"], "De Adelaarshorst", "Deventer", 52.2446, 6.1727, "ga-eagles.nl", "#e0303a"],
    ["nec", "NEC", ["NEC Nijmegen", "N.E.C."], "Goffertstadion", "Nijmegen", 51.8253, 5.8440, "nec-nijmegen.nl", "#e0303a"],
    ["pec-zwolle", "PEC Zwolle", ["Zwolle"], "MAC³PARK stadion", "Zwolle", 52.5128, 6.1172, "peczwolle.nl", "#3a7fd0"],
    ["psv", "PSV", ["PSV Eindhoven"], "Philips Stadion", "Eindhoven", 51.4417, 5.4675, "psv.nl", "#e8323b"],
    ["excelsior", "Excelsior", ["SBV Excelsior", "Excelsior Rotterdam"], "Van Donge & De Roo Stadion", "Rotterdam", 51.9164, 4.5206, "sbvexcelsior.nl", "#e0303a"],
    ["cambuur", "SC Cambuur", ["SC Cambuur-Leeuwarden", "Cambuur", "Cambuur Leeuwarden"], "Kooi Stadion", "Leeuwarden", 53.2005, 5.7684, "cambuur.nl", "#f2d21b"],
    ["heerenveen", "sc Heerenveen", ["Heerenveen"], "Abe Lenstra Stadion", "Heerenveen", 52.9587, 5.9375, "sc-heerenveen.nl", "#3a7fd0"],
    ["sparta", "Sparta Rotterdam", ["Sparta"], "Het Kasteel", "Rotterdam", 51.9193, 4.433, "sparta-rotterdam.nl", "#c72b39"],
    ["telstar", "Telstar", ["Telstar 1963", "SC Telstar"], "BUKO Stadion", "Velsen-Zuid", 52.4627, 4.6412, "sctelstar.nl", "#6cb4e4"],
    ["willem-ii", "Willem II", ["Willem II Tilburg"], "Koning Willem II Stadion", "Tilburg", 51.545, 5.068, "willem-ii.nl", "#e0303a"],
    ["dordrecht", "FC Dordrecht", ["Dordrecht"], "M-Scores Stadion", "Dordrecht", 51.8135, 4.6901, "fcdordrecht.nl", "#408657"],
  ]),
  ...group("DE", "Europe/Berlin", [
    ["koln", "1. FC Köln", ["FC Köln", "Köln", "1. FC Koeln"], "RheinEnergieSTADION", "Keulen", 50.9335, 6.8751, "fc.de", "#ed2030"],
    ["union-berlin", "Union Berlin", ["1. FC Union Berlin", "FC Union Berlin"], "Stadion An der Alten Försterei", "Berlijn", 52.4572, 13.5681, "fc-union-berlin.de", "#de2631"],
    ["mainz", "Mainz 05", ["1. FSV Mainz 05", "FSV Mainz 05", "Mainz"], "MEWA Arena", "Mainz", 49.9842, 8.2243, "mainz05.de", "#c8102e"],
    ["leverkusen", "Bayer Leverkusen", ["Bayer 04 Leverkusen", "Leverkusen"], "BayArena", "Leverkusen", 51.0383, 7.0022, "bayer04.de", "#e32834"],
    ["dortmund", "Borussia Dortmund", ["BV Borussia 09 Dortmund", "Dortmund", "BVB"], "Signal Iduna Park", "Dortmund", 51.4926, 7.4519, "bvb.de", "#edce2d"],
    ["gladbach", "Borussia Mönchengladbach", ["Bor. Mönchengladbach", "Mönchengladbach", "Gladbach", "Borussia M'gladbach"], "Borussia-Park", "Mönchengladbach", 51.1746, 6.3855, "borussia.de"],
    ["frankfurt", "Eintracht Frankfurt", ["Frankfurt"], "Deutsche Bank Park", "Frankfurt am Main", 50.0686, 8.6455, "eintracht.de", "#d93743"],
    ["augsburg", "FC Augsburg", ["Augsburg"], "WWK Arena", "Augsburg", 48.3233, 10.8856, "fcaugsburg.de", "#bb2031"],
    ["bayern", "Bayern München", ["FC Bayern München", "FC Bayern", "Bayern Munich", "Bayern"], "Allianz Arena", "München", 48.2188, 11.6247, "fcbayern.com", "#dc2339"],
    ["schalke", "Schalke 04", ["FC Schalke 04", "Schalke"], "Veltins-Arena", "Gelsenkirchen", 51.5545, 7.0676, "schalke04.de", "#2b80cf"],
    ["hsv", "Hamburger SV", ["HSV", "Hamburg"], "Volksparkstadion", "Hamburg", 53.5872, 9.8986, "hsv.de", "#3782d2"],
    ["leipzig", "RB Leipzig", ["RasenBallsport Leipzig", "Leipzig"], "Red Bull Arena", "Leipzig", 51.3458, 12.3483, "rbleipzig.com", "#ee324e"],
    ["freiburg", "SC Freiburg", ["Freiburg", "Sport-Club Freiburg"], "Europa-Park Stadion", "Freiburg im Breisgau", 48.0215, 7.8293, "scfreiburg.com", "#c93034"],
    ["paderborn", "SC Paderborn 07", ["SC Paderborn", "Paderborn"], "Home Deluxe Arena", "Paderborn", 51.7317, 8.7108, "scp07.de", "#248bd1"],
    ["elversberg", "SV Elversberg", ["SV 07 Elversberg", "Elversberg"], "Ursapharm-Arena an der Kaiserlinde", "Spiesen-Elversberg", 49.3186, 7.1217, "sv07elversberg.de"],
    ["werder", "Werder Bremen", ["SV Werder Bremen", "Bremen"], "Weserstadion", "Bremen", 53.0664, 8.8376, "werder.de", "#36a178"],
    ["hoffenheim", "TSG Hoffenheim", ["TSG 1899 Hoffenheim", "1899 Hoffenheim", "Hoffenheim"], "PreZero Arena", "Sinsheim", 49.238, 8.8877, "tsg-hoffenheim.de", "#3689d5"],
    ["stuttgart", "VfB Stuttgart", ["Stuttgart"], "MHPArena", "Stuttgart", 48.7923, 9.2321, "vfb.de", "#df2734"],
    ["wolfsburg", "VfL Wolfsburg", ["Wolfsburg"], "Volkswagen Arena", "Wolfsburg", 52.432, 10.8039, "vfl-wolfsburg.de", "#73bc39"],
    ["heidenheim", "1. FC Heidenheim", ["1. FC Heidenheim 1846", "FC Heidenheim", "Heidenheim"], "Voith-Arena", "Heidenheim an der Brenz", 48.6685, 10.1393, "fc-heidenheim.de", "#d43547"],
    ["st-pauli", "FC St. Pauli", ["FC St. Pauli 1910", "St. Pauli"], "Millerntor-Stadion", "Hamburg", 53.5546, 9.9677, "fcstpauli.com", "#b07a5a"],
    ["kaiserslautern", "1. FC Kaiserslautern", ["FC Kaiserslautern", "Kaiserslautern"], "Fritz-Walter-Stadion", "Kaiserslautern", 49.4347, 7.7767, "fck.de", "#e23b3b"],
    ["magdeburg", "1. FC Magdeburg", ["FC Magdeburg", "Magdeburg"], "Avnet Arena", "Maagdenburg", 52.1253, 11.6709, "fc-magdeburg.de", "#4a8fd6"],
    ["nurnberg", "1. FC Nürnberg", ["FC Nürnberg", "Nürnberg", "1. FC Nuernberg"], "Max-Morlock-Stadion", "Neurenberg", 49.4261, 11.1258, "fcn.de", "#d0344a"],
    ["bielefeld", "Arminia Bielefeld", ["DSC Arminia Bielefeld", "Bielefeld"], "SchücoArena", "Bielefeld", 52.0317, 8.5169, "arminia.de", "#3c78d8"],
    ["dresden", "Dynamo Dresden", ["SG Dynamo Dresden", "Dresden"], "Rudolf-Harbig-Stadion", "Dresden", 51.0408, 13.7478, "dynamo-dresden.de", "#f5c518"],
    ["braunschweig", "Eintracht Braunschweig", ["Braunschweig"], "Eintracht-Stadion", "Braunschweig", 52.29, 10.5217, "eintracht.com", "#f2c21b"],
    ["hannover", "Hannover 96", ["Hannover"], "Heinz von Heiden Arena", "Hannover", 52.3601, 9.7312, "hannover96.de", "#39a45b"],
    ["hertha", "Hertha BSC", ["Hertha Berlin", "Hertha"], "Olympiastadion", "Berlijn", 52.5147, 13.2394, "herthabsc.com", "#3a7fd5"],
    ["kiel", "Holstein Kiel", ["KSV Holstein", "Kiel"], "Holstein-Stadion", "Kiel", 54.349, 10.1236, "holstein-kiel.de", "#3a6fc4"],
    ["karlsruhe", "Karlsruher SC", ["Karlsruhe"], "BBBank Wildpark", "Karlsruhe", 49.02, 8.4131, "ksc.de", "#2f6fc6"],
    ["darmstadt", "SV Darmstadt 98", ["Darmstadt 98", "Darmstadt"], "Merck-Stadion am Böllenfalltor", "Darmstadt", 49.8578, 8.6725, "sv98.de", "#3f7fd0"],
    ["furth", "Greuther Fürth", ["SpVgg Greuther Fürth", "Fürth"], "Sportpark Ronhof", "Fürth", 49.4869, 10.9992, "sgf1903.de", "#39a45b"],
    ["bochum", "VfL Bochum", ["VfL Bochum 1848", "Bochum"], "Vonovia Ruhrstadion", "Bochum", 51.4899, 7.2365, "vfl-bochum.de", "#377cce"],
    ["osnabruck", "VfL Osnabrück", ["Osnabrück", "VfL Osnabrueck"], "Bremer Brücke", "Osnabrück", 52.28, 8.0719, "vfl.de", "#8a55c7"],
    ["cottbus", "Energie Cottbus", ["FC Energie Cottbus", "Cottbus"], "LEAG Energie Stadion", "Cottbus", 51.7516, 14.3444, "fcenergie.de", "#e0303a"],
    ["rw-essen", "Rot-Weiss Essen", ["Rot-Weiß Essen", "RW Essen"], "Stadion an der Hafenstraße", "Essen", 51.4867, 6.9764, "rot-weiss-essen.de", "#d8303c"],
    ["waldhof", "Waldhof Mannheim", ["SV Waldhof Mannheim", "SV Waldhof Mannheim 07", "SV Waldhof"], "Carl-Benz-Stadion", "Mannheim", 49.4794, 8.5025, "svw07.de", "#3a64c8"],
    ["verl", "SC Verl", ["Verl"], "Sportclub Arena", "Verl", 51.8835, 8.513, "scverl.de"],
    ["ingolstadt", "FC Ingolstadt 04", ["FC Ingolstadt", "Ingolstadt"], "Audi Sportpark", "Ingolstadt", 48.7456, 11.4856, "fcingolstadt.de", "#d7303b"],
    ["regensburg", "Jahn Regensburg", ["SSV Jahn Regensburg", "SSV Jahn", "Regensburg"], "Jahnstadion Regensburg", "Regensburg", 48.9906, 12.1078, "ssv-jahn.de", "#d2303a"],
    ["aachen", "Alemannia Aachen", ["TSV Alemannia Aachen", "Aachen"], "Tivoli", "Aken", 50.7934, 6.0971, "alemannia-aachen.de", "#f2c21b"],
    ["saarbrucken", "1. FC Saarbrücken", ["FC Saarbrücken", "Saarbrücken"], "Ludwigsparkstadion", "Saarbrücken", 49.2513, 6.9862, "fc-saarbruecken.de", "#3a64c8"],
    ["hoffenheim-ii", "TSG Hoffenheim II", ["TSG 1899 Hoffenheim II", "1899 Hoffenheim II", "Hoffenheim II"], "Dietmar-Hopp-Stadion", "Sinsheim-Hoffenheim", 49.2753, 8.8387, "tsg-hoffenheim.de", "#3689d5"],
    ["havelse", "TSV Havelse", ["Havelse"], "Eilenriedestadion", "Hannover", 52.3795, 9.7745, null],
    ["duisburg", "MSV Duisburg", ["Duisburg"], "Schauinsland-Reisen-Arena", "Duisburg", 51.4097, 6.7788, "msv-duisburg.de", "#3a7fd0"],
    ["stuttgart-ii", "VfB Stuttgart II", ["Stuttgart II"], "GAZi-Stadion auf der Waldau", "Stuttgart", 48.7573, 9.1826, "vfb.de", "#df2734"],
    ["rostock", "Hansa Rostock", ["F.C. Hansa Rostock", "FC Hansa Rostock", "Rostock"], "Ostseestadion", "Rostock", 54.085, 12.095, "fc-hansa.de", "#3a78d0"],
    ["viktoria-koln", "Viktoria Köln", ["FC Viktoria Köln", "FC Viktoria Köln 1904"], "Sportpark Höhenberg", "Keulen", 50.9469, 7.0346, "viktoria1904.de", "#d0303a"],
    ["wiesbaden", "Wehen Wiesbaden", ["SV Wehen Wiesbaden", "SV Wehen"], "BRITA-Arena", "Wiesbaden", 50.0714, 8.2553, "svww.de", "#d0303a"],
    ["munster", "Preußen Münster", ["SC Preußen Münster", "SC Preussen Münster", "Preussen Münster", "Münster"], "LVM-Preußenstadion", "Münster", 51.9303, 7.6258, "scpreussen-muenster.de", "#39a45b"],
    ["dusseldorf", "Fortuna Düsseldorf", ["Düsseldorf", "F95"], "Merkur Spiel-Arena", "Düsseldorf", 51.2617, 6.7331, "f95.de", "#e0303a"],
    ["grossaspach", "Sonnenhof Großaspach", ["SG Sonnenhof Großaspach", "SG Sonnenhof Grossaspach", "Großaspach"], "WIRmachenDRUCK Arena", "Aspach", 48.972, 9.392, null, "#3a7fd0"],
    ["meppen", "SV Meppen", ["Meppen"], "Hänsch-Arena", "Meppen", 52.693, 7.297, "svmeppen.de", "#3a7fd0"],
    ["fortuna-koln", "Fortuna Köln", ["SC Fortuna Köln"], "Südstadion", "Keulen", 50.9163, 6.9398, "fortuna-koeln.de", "#e0303a"],
    ["wurzburg", "Würzburger Kickers", ["FC Würzburger Kickers", "Kickers Würzburg"], "Akon Arena", "Würzburg", 49.778, 9.9338, "wuerzburger-kickers.de", "#e0303a"],
  ]),
  ...group("EN", "Europe/London", [
    ["bournemouth", "Bournemouth", ["AFC Bournemouth"], "Vitality Stadium", "Bournemouth", 50.7352, -1.8384, "afcb.co.uk", "#e0303a"],
    ["arsenal", "Arsenal", ["Arsenal FC"], "Emirates Stadium", "Londen", 51.5549, -0.1084, "arsenal.com", "#ef3340"],
    ["aston-villa", "Aston Villa", ["Aston Villa FC"], "Villa Park", "Birmingham", 52.5092, -1.8848, "avfc.co.uk", "#a3c5e9"],
    ["brentford", "Brentford", ["Brentford FC"], "Gtech Community Stadium", "Londen", 51.4907, -0.2887, "brentfordfc.com", "#e3303a"],
    ["brighton", "Brighton & Hove Albion", ["Brighton & Hove Albion FC", "Brighton and Hove Albion", "Brighton"], "American Express Stadium", "Brighton", 50.8618, -0.0833, "brightonandhovealbion.com", "#3b7fd4"],
    ["chelsea", "Chelsea", ["Chelsea FC"], "Stamford Bridge", "Londen", 51.4817, -0.191, "chelseafc.com", "#3a6fd8"],
    ["coventry", "Coventry City", ["Coventry City FC", "Coventry"], "Coventry Building Society Arena", "Coventry", 52.4481, -1.4956, "ccfc.co.uk", "#6cb4e4"],
    ["crystal-palace", "Crystal Palace", ["Crystal Palace FC"], "Selhurst Park", "Londen", 51.3983, -0.0855, "cpfc.co.uk", "#3a6fd0"],
    ["everton", "Everton", ["Everton FC"], "Hill Dickinson Stadium", "Liverpool", 53.4251, -3.0028, "evertonfc.com", "#3a64c8"],
    ["fulham", "Fulham", ["Fulham FC"], "Craven Cottage", "Londen", 51.475, -0.2217, "fulhamfc.com"],
    ["hull", "Hull City", ["Hull City AFC", "Hull"], "MKM Stadium", "Hull", 53.7462, -0.3678, "wearehullcity.co.uk", "#f5a623"],
    ["ipswich", "Ipswich Town", ["Ipswich Town FC", "Ipswich"], "Portman Road", "Ipswich", 52.0551, 1.1448, "itfc.co.uk", "#3a6fd0"],
    ["leeds", "Leeds United", ["Leeds United FC", "Leeds"], "Elland Road", "Leeds", 53.7778, -1.5722, "leedsunited.com", "#f2d23c"],
    ["liverpool", "Liverpool", ["Liverpool FC"], "Anfield", "Liverpool", 53.4308, -2.9608, "liverpoolfc.com", "#e03a4a"],
    ["man-city", "Manchester City", ["Manchester City FC", "Man City"], "Etihad Stadium", "Manchester", 53.4831, -2.2004, "mancity.com", "#6cabdd"],
    ["man-united", "Manchester United", ["Manchester United FC", "Man United", "Man Utd"], "Old Trafford", "Manchester", 53.4631, -2.2914, "manutd.com", "#e0403a"],
    ["newcastle", "Newcastle United", ["Newcastle United FC", "Newcastle"], "St James' Park", "Newcastle upon Tyne", 54.9756, -1.6217, "newcastleunited.com"],
    ["forest", "Nottingham Forest", ["Nottingham Forest FC", "Nott'm Forest", "Nottingham"], "City Ground", "Nottingham", 52.94, -1.1328, "nottinghamforest.co.uk", "#dd2b36"],
    ["sunderland", "Sunderland", ["Sunderland AFC"], "Stadium of Light", "Sunderland", 54.9146, -1.3884, "safc.com", "#e0303a"],
    ["tottenham", "Tottenham Hotspur", ["Tottenham Hotspur FC", "Tottenham", "Spurs"], "Tottenham Hotspur Stadium", "Londen", 51.6043, -0.0664, "tottenhamhotspur.com", "#c9d1e8"],
    ["birmingham", "Birmingham City", ["Birmingham City FC", "Birmingham"], "St Andrew's @ Knighthead Park", "Birmingham", 52.4757, -1.8682, "bcfc.com", "#3a64d0"],
    ["blackburn", "Blackburn Rovers", ["Blackburn Rovers FC", "Blackburn"], "Ewood Park", "Blackburn", 53.7286, -2.4892, "rovers.co.uk", "#3a7fd0"],
    ["bolton", "Bolton Wanderers", ["Bolton Wanderers FC", "Bolton"], "Toughsheet Community Stadium", "Bolton", 53.5806, -2.5356, "bwfc.co.uk"],
    ["bristol-city", "Bristol City", ["Bristol City FC"], "Ashton Gate", "Bristol", 51.44, -2.6203, "bcfc.co.uk", "#e0303a"],
    ["burnley", "Burnley", ["Burnley FC"], "Turf Moor", "Burnley", 53.7892, -2.2303, "burnleyfootballclub.com", "#a8d1ee"],
    ["charlton", "Charlton Athletic", ["Charlton Athletic FC", "Charlton"], "The Valley", "Londen", 51.4865, 0.0364, "cafc.co.uk", "#e0303a"],
    ["derby", "Derby County", ["Derby County FC", "Derby"], "Pride Park Stadium", "Derby", 52.915, -1.4472, "dcfc.co.uk"],
    ["lincoln", "Lincoln City", ["Lincoln City FC", "Lincoln"], "LNER Stadium", "Lincoln", 53.2183, -0.5408, "weareimps.com", "#e0303a"],
    ["middlesbrough", "Middlesbrough", ["Middlesbrough FC", "Boro"], "Riverside Stadium", "Middlesbrough", 54.5783, -1.2169, "mfc.co.uk", "#e0303a"],
    ["millwall", "Millwall", ["Millwall FC"], "The Den", "Londen", 51.4859, -0.0509, "millwallfc.co.uk", "#3a64c8"],
    ["norwich", "Norwich City", ["Norwich City FC", "Norwich"], "Carrow Road", "Norwich", 52.6221, 1.3087, "canaries.co.uk", "#f2d21b"],
    ["portsmouth", "Portsmouth", ["Portsmouth FC"], "Fratton Park", "Portsmouth", 50.7964, -1.0639, "portsmouthfc.co.uk", "#3a64d0"],
    ["preston", "Preston North End", ["Preston North End FC", "Preston"], "Deepdale", "Preston", 53.7722, -2.6883, "pnefc.net"],
    ["qpr", "Queens Park Rangers", ["Queens Park Rangers FC", "QPR"], "Loftus Road", "Londen", 51.5092, -0.2322, "qpr.co.uk", "#3a6fd0"],
    ["sheffield-united", "Sheffield United", ["Sheffield United FC", "Sheffield Utd"], "Bramall Lane", "Sheffield", 53.3703, -1.4709, "sufc.co.uk", "#e0303a"],
    ["southampton", "Southampton", ["Southampton FC"], "St Mary's Stadium", "Southampton", 50.9058, -1.3911, "southamptonfc.com", "#e0303a"],
    ["stoke", "Stoke City", ["Stoke City FC", "Stoke"], "bet365 Stadium", "Stoke-on-Trent", 52.9884, -2.1756, "stokecityfc.com", "#e0303a"],
    ["watford", "Watford", ["Watford FC"], "Vicarage Road", "Watford", 51.6498, -0.4015, "watfordfc.com", "#f2d21b"],
    ["west-brom", "West Bromwich Albion", ["West Bromwich Albion FC", "West Brom"], "The Hawthorns", "West Bromwich", 52.5092, -1.9639, "wba.co.uk", "#3a64c8"],
    ["west-ham", "West Ham United", ["West Ham United FC", "West Ham"], "London Stadium", "Londen", 51.5386, -0.0166, "whufc.com", "#a3c5e9"],
    ["wolves", "Wolverhampton Wanderers", ["Wolverhampton Wanderers FC", "Wolverhampton", "Wolves"], "Molineux Stadium", "Wolverhampton", 52.5903, -2.1303, "wolves.co.uk", "#fdb913"],
  ]),
  ...group("WA", "Europe/London", [
    ["cardiff", "Cardiff City", ["Cardiff City FC", "Cardiff"], "Cardiff City Stadium", "Cardiff", 51.4728, -3.2031, "cardiffcityfc.co.uk", "#3a6fd0"],
    ["swansea", "Swansea City", ["Swansea City AFC", "Swansea"], "Swansea.com Stadium", "Swansea", 51.6422, -3.9351, "swanseacity.com"],
    ["wrexham", "Wrexham", ["Wrexham AFC"], "STōK Cae Ras", "Wrexham", 53.0521, -3.0041, "wrexhamafc.co.uk", "#e0303a"],
  ]),
  ...group("ES", "Europe/Madrid", [
    ["athletic", "Athletic Club", ["Athletic Bilbao", "Athletic Club Bilbao"], "San Mamés", "Bilbao", 43.2641, -2.9494, "athletic-club.eus", "#e0303a"],
    ["osasuna", "Osasuna", ["CA Osasuna"], "El Sadar", "Pamplona", 42.7967, -1.637, "osasuna.es", "#d8303a"],
    ["atletico", "Atlético Madrid", ["Club Atlético de Madrid", "Atlético de Madrid", "Atletico Madrid", "Atleti"], "Riyadh Air Metropolitano", "Madrid", 40.4362, -3.5995, "atleticodemadrid.com", "#e0303a"],
    ["alaves", "Deportivo Alavés", ["Alavés"], "Mendizorroza", "Vitoria-Gasteiz", 42.8372, -2.6881, "deportivoalaves.com", "#3a6fd0"],
    ["elche", "Elche", ["Elche CF"], "Martínez Valero", "Elche", 38.2669, -0.6633, "elchecf.es", "#39a45b"],
    ["barcelona", "FC Barcelona", ["Barcelona", "Barça"], "Spotify Camp Nou", "Barcelona", 41.3809, 2.1228, "fcbarcelona.com", "#d0405a"],
    ["getafe", "Getafe", ["Getafe CF"], "Coliseum", "Getafe", 40.3256, -3.7147, "getafecf.com", "#3a6fd0"],
    ["levante", "Levante", ["Levante UD"], "Ciutat de València", "Valencia", 39.4947, -0.3642, "levanteud.com", "#4a6fd0"],
    ["malaga", "Málaga", ["Málaga CF"], "La Rosaleda", "Málaga", 36.7341, -4.4264, "malagacf.com", "#6cb4e4"],
    ["celta", "Celta", ["RC Celta de Vigo", "RC Celta", "Celta de Vigo", "Celta Vigo"], "Abanca-Balaídos", "Vigo", 42.2118, -8.7397, "rccelta.es", "#8ac5ef"],
    ["deportivo", "Deportivo La Coruña", ["RC Deportivo La Coruña", "RC Deportivo", "Deportivo de La Coruña", "Deportivo", "Dépor"], "Abanca-Riazor", "A Coruña", 43.3687, -8.4175, "rcdeportivo.es", "#3a6fd0"],
    ["espanyol", "Espanyol", ["RCD Espanyol de Barcelona", "RCD Espanyol", "Espanyol Barcelona"], "RCDE Stadium", "Cornellà de Llobregat", 41.3479, 2.0757, "rcdespanyol.com", "#3a7fd0"],
    ["rayo", "Rayo Vallecano", ["Rayo Vallecano de Madrid"], "Estadio de Vallecas", "Madrid", 40.3919, -3.659, "rayovallecano.es", "#e0303a"],
    ["betis", "Real Betis", ["Real Betis Balompié", "Betis"], "Estadio de La Cartuja", "Sevilla", 37.4164, -6.0045, "realbetisbalompie.es", "#39a45b"],
    ["real-madrid", "Real Madrid", ["Real Madrid CF"], "Santiago Bernabéu", "Madrid", 40.4531, -3.6883, "realmadrid.com"],
    ["racing", "Racing Santander", ["Real Racing Club de Santander", "Real Racing Club", "Racing de Santander"], "El Sardinero", "Santander", 43.4764, -3.7933, "realracingclub.es", "#39a45b"],
    ["real-sociedad", "Real Sociedad", ["Real Sociedad de Fútbol"], "Reale Arena", "San Sebastián", 43.3014, -1.9736, "realsociedad.eus", "#3a7fd0"],
    ["sevilla", "Sevilla", ["Sevilla FC"], "Ramón Sánchez-Pizjuán", "Sevilla", 37.384, -5.9706, "sevillafc.es", "#e0303a"],
    ["valencia", "Valencia", ["Valencia CF"], "Mestalla", "Valencia", 39.4747, -0.3584, "valenciacf.com", "#f0a030"],
    ["villarreal", "Villarreal", ["Villarreal CF"], "Estadio de la Cerámica", "Vila-real", 39.9442, -0.1036, "villarrealcf.es", "#f2d21b"],
  ]),
  ...group("IT", "Europe/Rome", [
    ["milan", "AC Milan", ["Milan"], "San Siro", "Milaan", 45.4781, 9.124, "acmilan.com", "#e0303a"],
    ["monza", "Monza", ["AC Monza"], "U-Power Stadium", "Monza", 45.5828, 9.3083, "acmonza.com", "#e0303a"],
    ["fiorentina", "Fiorentina", ["ACF Fiorentina"], "Stadio Artemio Franchi", "Florence", 43.7808, 11.2822, "acffiorentina.com", "#9a6fd0"],
    ["roma", "AS Roma", ["Roma"], "Stadio Olimpico", "Rome", 41.9341, 12.4547, "asroma.com", "#f0a030"],
    ["atalanta", "Atalanta", ["Atalanta BC"], "New Balance Arena", "Bergamo", 45.7089, 9.6808, "atalanta.it", "#3a6fd0"],
    ["bologna", "Bologna", ["Bologna FC 1909", "Bologna FC"], "Stadio Renato Dall'Ara", "Bologna", 44.4921, 11.3097, "bolognafc.it", "#d0303a"],
    ["cagliari", "Cagliari", ["Cagliari Calcio"], "Unipol Domus", "Cagliari", 39.1999, 9.1375, "cagliaricalcio.com", "#d0303a"],
    ["como", "Como", ["Como 1907"], "Stadio Giuseppe Sinigaglia", "Como", 45.8139, 9.0722, "comofootball.com", "#3a7fd0"],
    ["inter", "Inter", ["FC Internazionale Milano", "Internazionale", "Inter Milan", "Inter Milano"], "San Siro", "Milaan", 45.4781, 9.124, "inter.it", "#3a6fd0"],
    ["frosinone", "Frosinone", ["Frosinone Calcio"], "Stadio Benito Stirpe", "Frosinone", 41.6343, 13.3219, "frosinonecalcio.com", "#f2d21b"],
    ["genoa", "Genoa", ["Genoa CFC"], "Stadio Luigi Ferraris", "Genua", 44.4165, 8.9525, "genoacfc.it", "#d0303a"],
    ["juventus", "Juventus", ["Juventus FC", "Juve"], "Allianz Stadium", "Turijn", 45.1096, 7.6413, "juventus.com"],
    ["parma", "Parma", ["Parma Calcio 1913", "Parma Calcio"], "Stadio Ennio Tardini", "Parma", 44.795, 10.3384, "parmacalcio1913.com", "#f2d21b"],
    ["lazio", "Lazio", ["SS Lazio"], "Stadio Olimpico", "Rome", 41.9341, 12.4547, "sslazio.it", "#8ac5ef"],
    ["napoli", "Napoli", ["SSC Napoli"], "Stadio Diego Armando Maradona", "Napels", 40.828, 14.1931, "sscnapoli.it", "#4aa0e0"],
    ["torino", "Torino", ["Torino FC"], "Stadio Olimpico Grande Torino", "Turijn", 45.0418, 7.65, "torinofc.it", "#c05a5a"],
    ["lecce", "Lecce", ["US Lecce"], "Stadio Via del Mare", "Lecce", 40.3653, 18.2089, "uslecce.it", "#f2d21b"],
    ["sassuolo", "Sassuolo", ["US Sassuolo Calcio", "US Sassuolo"], "Mapei Stadium – Città del Tricolore", "Reggio Emilia", 44.7148, 10.6497, "sassuolocalcio.it", "#39a45b"],
    ["udinese", "Udinese", ["Udinese Calcio"], "Bluenergy Stadium", "Udine", 46.0817, 13.2003, "udinese.it"],
    ["venezia", "Venezia", ["Venezia FC"], "Stadio Pier Luigi Penzo", "Venetië", 45.4274, 12.3638, "veneziafc.it", "#f08a30"],
  ]),
  ...group("FR", "Europe/Paris", [
    ["auxerre", "Auxerre", ["AJ Auxerre"], "Stade de l'Abbé-Deschamps", "Auxerre", 47.7868, 3.5887, "aja.fr", "#3a7fd0"],
    ["angers", "Angers SCO", ["SCO Angers", "Angers"], "Stade Raymond-Kopa", "Angers", 47.4604, -0.5307, "angers-sco.fr"],
    ["troyes", "Troyes", ["ES Troyes AC", "ESTAC Troyes", "ESTAC"], "Stade de l'Aube", "Troyes", 48.3076, 4.0985, "estac.fr", "#3a7fd0"],
    ["lorient", "Lorient", ["FC Lorient"], "Stade du Moustoir", "Lorient", 47.7487, -3.3694, "fclweb.fr", "#f08a30"],
    ["le-havre", "Le Havre", ["Le Havre AC", "HAC"], "Stade Océane", "Le Havre", 49.4988, 0.1697, "hac-foot.com", "#6cb4e4"],
    ["le-mans", "Le Mans", ["Le Mans FC"], "MMArena", "Le Mans", 47.9577, 0.2244, "lemansfc.fr", "#e0303a"],
    ["lille", "Lille", ["Lille OSC", "LOSC Lille", "LOSC"], "Stade Pierre-Mauroy", "Villeneuve-d'Ascq", 50.6119, 3.1304, "losc.fr", "#e0303a"],
    ["nice", "Nice", ["OGC Nice"], "Allianz Riviera", "Nice", 43.7053, 7.1926, "ogcnice.com", "#e0303a"],
    ["lyon", "Olympique Lyonnais", ["Lyon", "OL"], "Groupama Stadium", "Décines-Charpieu", 45.7653, 4.982, "ol.fr", "#3a6fd0"],
    ["marseille", "Olympique de Marseille", ["Olympique Marseille", "Marseille", "OM"], "Orange Vélodrome", "Marseille", 43.2698, 5.3959, "om.fr", "#6cb4e4"],
    ["paris-fc", "Paris FC", [], "Stade Jean-Bouin", "Parijs", 48.8432, 2.2528, "parisfc.fr", "#8ab4e8"],
    ["psg", "Paris Saint-Germain", ["Paris Saint-Germain FC", "Paris SG", "PSG"], "Parc des Princes", "Parijs", 48.8414, 2.253, "psg.fr", "#3a6fd8"],
    ["strasbourg", "Strasbourg", ["RC Strasbourg Alsace", "RC Strasbourg", "Racing Strasbourg"], "Stade de la Meinau", "Straatsburg", 48.5601, 7.755, "rcstrasbourgalsace.fr", "#3a7fd0"],
    ["lens", "RC Lens", ["Racing Club de Lens", "Lens"], "Stade Bollaert-Delelis", "Lens", 50.4329, 2.815, "rclens.fr", "#f2d21b"],
    ["brest", "Stade Brestois", ["Stade Brestois 29", "Brest"], "Stade Francis-Le Blé", "Brest", 48.4029, -4.4617, "sb29.bzh", "#e0303a"],
    ["rennes", "Stade Rennais", ["Stade Rennais FC 1901", "Stade Rennais FC", "Rennes"], "Roazhon Park", "Rennes", 48.1075, -1.7128, "staderennais.com", "#e0303a"],
    ["toulouse", "Toulouse", ["Toulouse FC"], "Stadium de Toulouse", "Toulouse", 43.5831, 1.4342, "toulousefc.com", "#9a6fd0"],
  ]),
  ...group("MC", "Europe/Monaco", [
    ["monaco", "AS Monaco", ["AS Monaco FC", "Monaco"], "Stade Louis II", "Monaco", 43.7276, 7.4156, "asmonaco.com", "#e0303a"],
  ]),
  ...group("PT", "Europe/Lisbon", [
    ["academico-viseu", "Académico de Viseu", ["Académico de Viseu FC", "Académico Viseu", "Academico Viseu"], "Estádio do Fontelo", "Viseu", 40.6585, -7.907, null],
    ["nacional", "Nacional", ["CD Nacional", "Nacional da Madeira"], "Estádio da Madeira", "Funchal", 32.6711, -16.8847, null, undefined, "Atlantic/Madeira"],
    ["santa-clara", "Santa Clara", ["CD Santa Clara"], "Estádio de São Miguel", "Ponta Delgada", 37.7482, -25.6592, null, "#e0303a", "Atlantic/Azores"],
    ["estrela", "Estrela da Amadora", ["CF Estrela da Amadora", "Estrela Amadora"], "Estádio José Gomes", "Amadora", 38.7527, -9.2244, null, "#e0303a"],
    ["maritimo", "Marítimo", ["CS Marítimo", "Maritimo"], "Estádio do Marítimo", "Funchal", 32.6468, -16.9269, "csmaritimo.org.pt", "#e0303a", "Atlantic/Madeira"],
    ["casa-pia", "Casa Pia", ["Casa Pia AC"], "Estádio Municipal de Rio Maior", "Rio Maior", 39.336, -8.939, "casapiaac.pt"],
    ["alverca", "FC Alverca", ["Alverca"], "Complexo Desportivo FC Alverca", "Alverca do Ribatejo", 38.8989, -9.0406, "fcalvercafutebolsad.pt", "#3a7fd0"],
    ["arouca", "Arouca", ["FC Arouca"], "Estádio Municipal de Arouca", "Arouca", 40.9311, -8.2481, null, "#f2d21b"],
    ["famalicao", "Famalicão", ["FC Famalicão", "Famalicao"], "Estádio Municipal 22 de Junho", "Vila Nova de Famalicão", 41.402, -8.5212, "fcfamalicao.pt", "#3a7fd0"],
    ["porto", "FC Porto", ["Porto"], "Estádio do Dragão", "Porto", 41.1618, -8.5839, "fcporto.pt", "#3a7fd0"],
    ["estoril", "Estoril Praia", ["GD Estoril Praia", "Estoril"], "Estádio António Coimbra da Mota", "Estoril", 38.709, -9.3985, "estorilpraia.pt", "#f2d21b"],
    ["gil-vicente", "Gil Vicente", ["Gil Vicente FC"], "Estádio Cidade de Barcelos", "Barcelos", 41.548, -8.6273, null, "#e0303a"],
    ["moreirense", "Moreirense", ["Moreirense FC"], "Parque de Jogos Comendador Joaquim de Almeida Freitas", "Moreira de Cónegos", 41.3792, -8.3486, null, "#39a45b"],
    ["rio-ave", "Rio Ave", ["Rio Ave FC"], "Estádio do Rio Ave FC", "Vila do Conde", 41.3615, -8.7404, "rioavefc.pt", "#39a45b"],
    ["benfica", "Benfica", ["Sport Lisboa e Benfica", "SL Benfica"], "Estádio da Luz", "Lissabon", 38.7527, -9.1847, "slbenfica.pt", "#e0303a"],
    ["braga", "SC Braga", ["Sporting Clube de Braga", "Sporting Braga", "Braga"], "Estádio Municipal de Braga", "Braga", 41.5626, -8.4298, "scbraga.pt", "#e0303a"],
    ["sporting", "Sporting CP", ["Sporting Clube de Portugal", "Sporting Lisbon", "Sporting"], "Estádio José Alvalade", "Lissabon", 38.7612, -9.1609, "sporting.pt", "#39a45b"],
    ["vitoria", "Vitória SC", ["Vitória Guimarães", "Vitória de Guimarães", "Vitoria Guimaraes"], "Estádio D. Afonso Henriques", "Guimarães", 41.4459, -8.3007, "vitoriasc.pt"],
  ]),
];

export const clubById = (id: string) => CLUBS.find((c) => c.id === id);
